apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tenant-a-secrets
  namespace: tenant-a
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "tenant-a/database-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
      - objectName: "tenant-a/api-keys"
        objectType: "secretsmanager"
        jmesPath:
          - path: "api_key"
            objectAlias: "api-key"
          - path: "webhook_secret"
            objectAlias: "webhook-secret"
      - objectName: "tenant-a/environment"
        objectType: "secretsmanager"
        jmesPath:
          - path: "environment"
            objectAlias: "environment"
    usePodIdentity: "true"
  secretObjects:
  - secretName: tenant-a-database-secret
    type: Opaque
    data:
    - objectName: db-username
      key: username
    - objectName: db-password
      key: password
  - secretName: tenant-a-api-secret
    type: Opaque
    data:
    - objectName: api-key
      key: api_key
    - objectName: webhook-secret
      key: webhook_secret
  - secretName: tenant-a-environment
    type: Opaque
    data:
    - objectName: environment
      key: environment
